import 'package:json_annotation/json_annotation.dart';
import 'package:equatable/equatable.dart';
import 'package:cloud_firestore/cloud_firestore.dart'; // Import for Timestamp

part 'pregnancy_details.g.dart';

@JsonSerializable(explicitToJson: true)
class PregnancyDetails extends Equatable {
  final String? userId; // Make userId nullable if it can be missing initially

  // Store dates consistently - Using DateTime internally is often easier in Dart
  // Use JsonKey to handle conversion to/from Firestore Timestamp (or int/String for JSON)
  @JsonKey(fromJson: _dateTimeFromTimestamp, toJson: _dateTimeToTimestamp)
  final DateTime startingDay;

  final int weeksPregnant;
  final int daysPregnant;
  final double babyHeight;
  final double babyWeight;

  @JsonKey(fromJson: _dateTimeFromTimestamp, toJson: _dateTimeToTimestamp)
  final DateTime dueDate;

  const PregnancyDetails({
    required this.userId, // Allow null userId
    required this.startingDay,
    required this.weeksPregnant,
    required this.daysPregnant,
    required this.babyHeight,
    required this.babyWeight,
    required this.dueDate,
  });

  // --- Corrected Static Conversion Methods ---
  // For converting Firestore Timestamp TO DateTime during deserialization (fromJson)
  static DateTime _dateTimeFromTimestamp(Timestamp timestamp) {
    return timestamp.toDate();
  }

  // For converting DateTime TO Firestore Timestamp during serialization (toJson)
  static Timestamp _dateTimeToTimestamp(DateTime dateTime) {
    return Timestamp.fromDate(dateTime);
  }
  // -------------------------------------------

  // --- Alternative Conversion Methods (if storing as milliseconds int in JSON/DB) ---
  // static DateTime _dateTimeFromMilliseconds(int milliseconds) {
  //   return DateTime.fromMillisecondsSinceEpoch(milliseconds);
  // }
  // static int _dateTimeToMilliseconds(DateTime dateTime) {
  //   return dateTime.millisecondsSinceEpoch;
  // }
  // -------------------------------------------


  // Calculated properties (Removed startDate as startingDay is now DateTime)
  int get currentWeek => weeksPregnant;
  int get totalDaysPregnant => daysPregnant + (weeksPregnant * 7);
  DateTime get estimatedConceptionDate => dueDate.subtract(const Duration(days: 266)); // Average 266 days from conception

  // JSON Serialization (Generated by build_runner)
  factory PregnancyDetails.fromJson(Map<String, dynamic> json) =>
      _$PregnancyDetailsFromJson(json);

  // toJson method (Generated by build_runner)
  // Remove the parameter if userId is part of the class fields handled by generation
  Map<String, dynamic> toJson() => _$PregnancyDetailsToJson(this);

  // Copy with method - Ensure types match the class fields
  PregnancyDetails copyWith({
    String? userId,
    DateTime? startingDay, // Changed to DateTime?
    int? weeksPregnant,
    int? daysPregnant,
    double? babyHeight,
    double? babyWeight,
    DateTime? dueDate, // Changed to DateTime?
  }) {
    return PregnancyDetails(
      // Handle potential null userId during copyWith
      userId: userId ?? this.userId,
      startingDay: startingDay ?? this.startingDay,
      weeksPregnant: weeksPregnant ?? this.weeksPregnant,
      daysPregnant: daysPregnant ?? this.daysPregnant,
      babyHeight: babyHeight ?? this.babyHeight,
      babyWeight: babyWeight ?? this.babyWeight,
      dueDate: dueDate ?? this.dueDate,
    );
  }

  @override
  List<Object?> get props => [
        userId,
        startingDay,
        weeksPregnant,
        daysPregnant,
        babyHeight,
        babyWeight,
        dueDate,
      ];

  // Calculated property for days remaining (example)
  int? get daysRemaining {
      final now = DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day);
      final due = DateTime(dueDate.year, dueDate.month, dueDate.day);
      if (due.isBefore(now)) {
         return null; // Or return negative number if needed
      }
      return due.difference(now).inDays;
  }
}