// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmwgDtSeTwPz5FEvFFJQcX6dgHrYE2qSk',
    appId: '1:659099084415:web:d00277d40d9841c98b814a',
    messagingSenderId: '659099084415',
    projectId: 'mamacare-2cf36',
    authDomain: 'mamacare-2cf36.firebaseapp.com',
    databaseURL: 'https://mamacare-2cf36-default-rtdb.firebaseio.com',
    storageBucket: 'mamacare-2cf36.firebasestorage.app',
    measurementId: 'G-MQQ52HVNLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASOP9FPuph_-7jas9_spH8BMe2EyvMfGE',
    appId: '1:659099084415:android:64f1537779f86db68b814a',
    messagingSenderId: '659099084415',
    projectId: 'mamacare-2cf36',
    databaseURL: 'https://mamacare-2cf36-default-rtdb.firebaseio.com',
    storageBucket: 'mamacare-2cf36.firebasestorage.app',
  );

  // Using web configuration for iOS as fallback
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmwgDtSeTwPz5FEvFFJQcX6dgHrYE2qSk',
    appId: '1:659099084415:web:d00277d40d9841c98b814a',
    messagingSenderId: '659099084415',
    projectId: 'mamacare-2cf36',
    authDomain: 'mamacare-2cf36.firebaseapp.com',
    databaseURL: 'https://mamacare-2cf36-default-rtdb.firebaseio.com',
    storageBucket: 'mamacare-2cf36.firebasestorage.app',
    measurementId: 'G-MQQ52HVNLE',
  );

  // Using web configuration for macOS as fallback
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmwgDtSeTwPz5FEvFFJQcX6dgHrYE2qSk',
    appId: '1:659099084415:web:d00277d40d9841c98b814a',
    messagingSenderId: '659099084415',
    projectId: 'mamacare-2cf36',
    authDomain: 'mamacare-2cf36.firebaseapp.com',
    databaseURL: 'https://mamacare-2cf36-default-rtdb.firebaseio.com',
    storageBucket: 'mamacare-2cf36.firebasestorage.app',
    measurementId: 'G-MQQ52HVNLE',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmwgDtSeTwPz5FEvFFJQcX6dgHrYE2qSk',
    appId: '1:659099084415:web:2ad35c28bf6990088b814a',
    messagingSenderId: '659099084415',
    projectId: 'mamacare-2cf36',
    authDomain: 'mamacare-2cf36.firebaseapp.com',
    databaseURL: 'https://mamacare-2cf36-default-rtdb.firebaseio.com',
    storageBucket: 'mamacare-2cf36.firebasestorage.app',
    measurementId: 'G-79Y0HVXEMY',
  );

  // Using web configuration for Linux as fallback
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDmwgDtSeTwPz5FEvFFJQcX6dgHrYE2qSk',
    appId: '1:659099084415:web:d00277d40d9841c98b814a',
    messagingSenderId: '659099084415',
    projectId: 'mamacare-2cf36',
    authDomain: 'mamacare-2cf36.firebaseapp.com',
    databaseURL: 'https://mamacare-2cf36-default-rtdb.firebaseio.com',
    storageBucket: 'mamacare-2cf36.firebasestorage.app',
    measurementId: 'G-MQQ52HVNLE',
  );
}
